Adds optional combinator, changes pipeline to required
BrianHicks/elm-csv pull request #29
Opened 2023-06-20 16:07 UTC by gampleman

Fixes #23.

2023-06-26 18:06 UTC, BrianHicks requested changes
really great start. Thank you for doing this! Just a few things to fix and we'll be good to go.

2023-06-26 18:06 UTC, BrianHicks commented on src/Csv/Decode.elm
> +}
I think the formatting got squished a little here

2023-06-26 18:06 UTC, BrianHicks commented on tests/Csv/DecodeTest.elm
> +    describe "optional"
could you add a test showing a successful decode when the field is present?

2023-06-26 18:06 UTC, BrianHicks commented on tests/Csv/DecodeTest.elm
> +        [ test "succeds when missing column" <|
```suggestion
        [ test "succeeds when missing column" <|
```

just a tiny change here!

2024-03-06 12:25 UTC, BrianHicks commented
if we're making a major change, this one seems worth including to me. Are you interested in getting the conflicts fixed and getting it up and running again?

2024-03-24 08:11 UTC, gampleman commented
Sorry, started looking into this, but didn't we already do https://github.com/BrianHicks/elm-csv/pull/30? This is sort of the same thing?

2024-03-24 10:51 UTC, BrianHicks commented
Yeah, that’s fair. Thanks for pointing that out. I was just looking over open PRs and liked the optional/required distinction here. 

Ok to close then?

2024-03-24 17:05 UTC, gampleman commented
Yeah let’s close

2024-03-24 17:05 UTC, closed without merging